refactor: break down `@core` into `@0_fancy-cli` and `@1_core`

diff --git a/modules/@0_fancy-cli/scripts/jot b/modules/@0_fancy-cli/scripts/jot
--- a/modules/@0_fancy-cli/scripts/jot
+++ b/modules/@0_fancy-cli/scripts/jot
@@ -1,10 +1,10 @@
 #!/usr/bin/env dash
 
-# shellcheck source=../functions/stdin-or
-. "$CORE_FUNCTIONS/stdin-or"
+# shellcheck source=../../functions/stdin-or
+. "$FCLI_FUNCTIONS/stdin-or"
 
-# shellcheck source=../functions/predicates
-. "$CORE_FUNCTIONS/predicates"
+# shellcheck source=../../functions/predicates
+. "$FCLI_FUNCTIONS/predicates"
 
 # NAME
 #  jot - Quickly write text in Neovim and echo it to the terminal.
@@ -41,22 +41,16 @@
 # SEE ALSO
 #  nvim(1), alacritty(1), log(1)
 
-# ╭───┤ Before we begin
-# ╰─
-
-log_error() {
-  # /dev/tty redirect is used to ensure log does not inherit 
-  # parent's stdin
-  log "$@" "jot" < /dev/tty;
-}
+export LOG_NAMESPACE="jot"
+export LOG_LEVEL="info"
 
 if ! does_command_exist alacritty; then
-  log_error "alacritty is not installed, exiting"
+  fancy-log error "alacritty is not installed, exiting"
   exit 1
 fi
 
 if ! does_command_exist nvim; then
-  log_error "nvim is not installed, exiting"
+  fancy-log error "nvim is not installed, exiting"
   exit 1
 fi
 
@@ -75,10 +69,6 @@ fi
 # ╭───┤ Functions
 # ╰─
 
-log_info() { 
-  log --type info "$@" "jot" < /dev/tty;
-}
-
 # Parse command-line options and set global variables.
 parse_options() {
   while [ "$#" -gt 0 ]; do
@@ -92,7 +82,7 @@ parse_options() {
         shift
         ;;
       --) shift; break ;;
-      -?*) log_error "unknown flag: $1"; exit 1 ;;
+      -?*) fancy-log error "unknown flag: $1"; exit 1 ;;
       *) break ;;
     esac
   done
@@ -108,7 +98,7 @@ decide_tmp_file() {
     TMP_FILE=$(mktemp /tmp/jot.XXXXXX)
 
     if [ -z "$TMP_FILE" ]; then
-      log_error "could not create temporary file, exiting"
+      fancy-log error "could not create temporary file, exiting"
       exit 1
     fi
   fi
@@ -123,7 +113,7 @@ decide_tmp_file() {
 add_stdin_to_file() {
   input=$(stdin_or "")
   if [ -n "$input" ]; then
-    printf "\n\`\`\`%s\n\`\`\`" "$input" >> "$TMP_FILE"
+    printf "%s" "$input" >> "$TMP_FILE"
   fi
 }
 
@@ -148,7 +138,7 @@ persist_and_output_note() {
     printf "%s" "$text"
     echo "$TMP_FILE" > "$PREV_NOTE_PATH"
   else
-    log_info "no text entered, nothing to do, exiting"
+    fancy-log info -v exit_code 0 "No text entered, nothing to do"
     exit 0
   fi
 }
