refactor(openai): use dash, folder restructure, use printf :facepalm:

diff --git a/new/modules/openai/libs/openai-api/ai-openai-completions b/new/modules/openai/libs/openai-api/ai-openai-completions
--- a/new/modules/openai/libs/openai-api/ai-openai-completions
+++ b/new/modules/openai/libs/openai-api/ai-openai-completions
@@ -1,10 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
+
+. "$CORE_FUNCTIONS/stdin-or"
 
 # NAME
 #  openai-api-completions - Call POST: /chat/completions 
 #
 # SYNOPSIS
-#  openai-api-completions [...options] <query> 
+#  openai-api-completions <-m|--model> <model> [-t|--temperature <value>] [--no-stream] <query>
 #
 # DESCRIPTION
 #  Low-level script that sends a query to OpenAI's chat endpoint and returns 
@@ -14,15 +16,22 @@
 #  https://platform.openai.com/docs/api-reference/chat
 #
 # ARGUMENTS
-#  <query>          The query to send to OpenAI
+#  <query>
+#   The query to send to OpenAI
 #
 # OPTIONS
-#  -t|--temperature The temperature to use for the completion. (default: 0.7)
-#  -m|--model       The model to use for the completion.
-#  --no-stream      Disable streaming OpenAI's response. (default: true)
+#  -m, --model <model>
+#   The model to use for the completion.
+#
+#  -t, --temperature [value=0.7]
+#   The temperature to use for the completion.
+#
+#  --no-stream
+#   Disable streaming OpenAI's response. (default: true)
 #
 # ENVIRONMENT
-#  OPENAI_API_KEY   The API key used for authenticating with the OpenAI API. 
+#  OPENAI_API_KEY
+#   The API key used for authenticating with the OpenAI API. 
 # 
 # EXAMPLES
 #  openai-api-completions "What is the meaning of life?"
@@ -32,17 +41,20 @@
 # SEE ALSO
 #  curl(1), jq(1)
 
+# ╭───┤ Outside dependencies 
+# ╰─
 if [ -z "$OPENAI_API_KEY" ]; then
   echo "error: missing environment variable OPENAI_API_KEY." >&2
-  exit 1 
+  exit 1
 fi
 
-# Default values
-temperature=0.7
-model=""
+# ╭───┤ Input and default values
+# ╰─
 should_stream=true
+temperature=0.7
 
-# Parse arguments
+# ╭───┤ Input validation
+# ╰─
 while [ "$#" -gt 0 ]; do
   case $1 in
     --no-stream)
@@ -65,16 +77,16 @@ while [ "$#" -gt 0 ]; do
       fi
     ;;
     --) shift; break ;;
-    -?*) 
-      echo "error: unknown flag: $1" >&2
-      exit 1 
-    ;;
+    -?*) echo "error: unknown flag: $1" >&2; exit 1 ;;
     *) break ;;
   esac
   shift
 done
 
-if [ -z "$1" ]; then
+# Read after flags are parsed and shifted out of $@
+query=$(stdin_or "$1")
+
+if [ -z "$query" ]; then
   echo "error: missing question, pass it as first parameter or pipe to stdin" >&2
   exit 1 
 fi
@@ -84,14 +96,16 @@ if [ -z "$model" ]; then
   exit 1 
 fi
 
-# If streaming, disable curl's buffering
-stream_curl_flags=""
-if [ $should_stream = true ]; then
-  stream_curl_flags="--no-buffer"
+# ╭──────────────────────
+# │ Main. Start here.
+# ╰────────
+
+if [ "$should_stream" = "true" ]; then
+  curl_stream_flags="--no-buffer"
 fi
 
-json_payload=$(jq --compact-output --null-input \
-  --arg question "$1" \
+jq --compact-output --null-input \
+  --arg question "$query" \
   --arg model "$model" \
   --arg stream "$should_stream" \
   --arg temperature "$temperature" \
@@ -100,15 +114,12 @@ json_payload=$(jq --compact-output --null-input \
     stream: ($stream | test("true")),
     messages: [{role: "user", content: $question}],
     temperature: ($temperature | tonumber)
-  }'
-)
-
-# Execute curl and write stdout to the pipe, stderr to a temp file
-curl --silent $stream_curl_flags \
+  }' \
+ | curl --silent "$curl_stream_flags" \
+  --data @- \
   --fail-with-body \
+  --request POST \
   --header "Content-Type: application/json" \
   --header "Authorization: Bearer $OPENAI_API_KEY" \
   --header "OpenAI-Organization: $OPENAI_ORG_ID" \
-  --data "$json_payload" \
   https://api.openai.com/v1/chat/completions
-
diff --git a/new/modules/openai/libs/sqlite-orm/ai-db-create b/new/modules/openai/libs/sqlite-orm/ai-db-create
--- a/new/modules/openai/libs/sqlite-orm/ai-db-create
+++ b/new/modules/openai/libs/sqlite-orm/ai-db-create
@@ -1,6 +1,6 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
-. "$CORE_LIBS/stdin-or"
+. "$CORE_FUNCTIONS/stdin-or"
 
 # NAME
 #  ai-db-create - Create a new record in a given table
@@ -34,7 +34,8 @@
 # SEE ALSO
 #  sqlite3(1), jq(1)
 
-# Parse flags
+# ╭───┤ Input validation 
+# ╰─
 while [ "$#" -gt 0 ]; do
   case $1 in
     -t|--table)
@@ -46,28 +47,27 @@ while [ "$#" -gt 0 ]; do
       fi
     ;;
     --) shift; break ;;
-    -?*)
-      echo "error: unknown flag $1" >&2
-      exit 1
-    ;;
+    -?*) echo "error: unknown flag $1" >&2; exit 1 ;;
     *) break ;;
   esac
   shift
 done
 
-# Input validation
 if [ -z "$table" ]; then
   echo "error: missing required flag -t|--table" >&2
   exit 1
 fi
 
-# Main
+# ╭──────────────────────
+# │ Main. Start here.
+# ╰────────
+
 json_data=$(stdin_or "$1")
 
 if [ -z "$json_data" ] || [ "$json_data" = "{}" ]; then
   insert_statement="INSERT INTO $table DEFAULT VALUES;"
 else
-  insert_statement=$(echo "$json_data" \
+  insert_statement=$(printf "%s" "$json_data" \
     | jq --raw-output --arg table "$table" \
     "# Function to escape string for SQLite
     def sqlite_escape:
@@ -104,4 +104,4 @@ COMMIT;
 EOF
 )
 
-echo "$data" | jq --raw-output --compact-output --monochrome-output '.[0]'
+printf "%s" "$data" | jq '.[0]'
diff --git a/new/modules/openai/libs/sqlite-orm/ai-db-find-many b/new/modules/openai/libs/sqlite-orm/ai-db-find-many
--- a/new/modules/openai/libs/sqlite-orm/ai-db-find-many
+++ b/new/modules/openai/libs/sqlite-orm/ai-db-find-many
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
 # NAME 
 #  ai-db-find-many - Find all or multiple records for a given table
@@ -26,6 +26,12 @@
 #   A comma separated list of related tables to include in the query.
 #   All fields from the related tables will be included in the result.
 #
+#  -s, --sort [sort_clause]
+#   The sort clause to use when querying the database. Defaults to "id ASC".
+#
+#  -m, --mode [mode="json"] 
+#   The display mode. Get's passed to sqlite3.
+#
 # ERROR CODES
 #  1 Input error: unknown flag provided, missing value for flag or missing
 #    required flag
@@ -47,55 +53,6 @@
 # SEE ALSO
 #  sqlite3(1)
 
-FILTER="*"
-WHERE=""
-MAIN_TABLE=""
-RELATED=""
-
-validate_flag() {
-  if [ -z "$2" ] || [ "${2#-}" != "$2" ]; then
-    echo "error: argument $1 requires a value" >&2
-    exit 1
-  fi
-}
-
-parse_flags() {
-  while [ "$#" -gt 0 ]; do
-    case $1 in
-      -f|--filter)
-        validate_flag "$1" "$2"
-        FILTER=$2; shift
-        ;;
-      -w|--where)
-        validate_flag "$1" "$2"
-        WHERE=$2; shift
-        ;;
-      -t|--table)
-        validate_flag "$1" "$2"
-        MAIN_TABLE=$2; shift
-        ;;
-      -i|--include)
-        validate_flag "$1" "$2"
-        RELATED=$2; shift
-        ;;
-      --) shift; break ;;
-      -?*) echo "error: unknown flag $1" >&2; exit 1 ;;
-      *) break ;;
-    esac
-    shift
-  done
-}
-
-query_database() {
-  query="SELECT $FILTER FROM $MAIN_TABLE"
-  
-  if [ -n "$WHERE" ] ; then
-    query="$query WHERE $WHERE"
-  fi
-
-  sqlite3 --json "$OPENAI_DB_FILE" "$query"
-}
-
 # 1:1 or N:1 relationships
 attach_direct_relationships() {
   related_table="$1"
@@ -110,7 +67,7 @@ attach_direct_relationships() {
   )
 
   # Attach related items, only those matching the ids from the main items
-  MAIN_ITEMS=$(jq --null-input --compact-output \
+  MAIN_ITEMS=$(jq --null-input \
     --argjson main_items "$MAIN_ITEMS" \
     --argjson related_items "$related_items" \
     '$main_items | map((. as $item | . + { 
@@ -133,7 +90,7 @@ attach_inverse_relationships() {
   )
 
   # Attach related items, only those matching the ids from the main items
-  MAIN_ITEMS=$(jq --null-input --compact-output \
+  MAIN_ITEMS=$(jq --null-input \
     --argjson main_items "$MAIN_ITEMS" \
     --argjson related_items "$related_items" \
     '$main_items | map((. as $item | . + { 
@@ -145,8 +102,8 @@ attach_inverse_relationships() {
 }
 
 attach_related_models() {
-  main_items_ids=$(echo "$MAIN_ITEMS" | jq '.[].id' | tr '\n' ',' | sed 's/,$//')
-  main_table_lower=$(echo "$MAIN_TABLE" | tr '[:upper:]' '[:lower:]')
+  main_items_ids=$(printf "%s" "$MAIN_ITEMS" | jq '.[].id' | tr '\n' ',' | sed 's/,$//')
+  main_table_lower=$(printf "%s" "$MAIN_TABLE" | tr '[:upper:]' '[:lower:]')
 
   # For each related table, query the database and add the related items to the 
   # main items using the related table name as the key.
@@ -169,26 +126,80 @@ attach_related_models() {
   done
 }
 
-# Main
-parse_flags "$@"
+# ╭───┤ Input validation
+# ╰─
+
+validate_flag() {
+  if [ -z "$2" ] || [ "${2#-}" != "$2" ]; then
+    echo "error: argument $1 requires a value" >&2
+    exit 1
+  fi
+}
+
+parse_args() {
+  while [ "$#" -gt 0 ]; do
+    case $1 in
+      -f|--filter)
+        validate_flag "$1" "$2"
+        FILTER=$2; shift
+      ;;
+      -w|--where)
+        validate_flag "$1" "$2"
+        WHERE=$2; shift
+      ;;
+      -t|--table)
+        validate_flag "$1" "$2"
+        MAIN_TABLE=$2; shift
+      ;;
+      -i|--include)
+        validate_flag "$1" "$2"
+        RELATED=$2; shift
+      ;;
+      -s|--sort)
+        validate_flag "$1" "$2"
+        SORT=$2; shift
+      ;;
+      -m|--mode)
+        validate_flag "$1" "$2"
+        MODE=$2; shift
+      ;;
+      --) shift; break ;;
+      -?*) echo "error: unknown flag $1" >&2; exit 1 ;;
+      *) break ;;
+    esac
+    shift
+  done
+}
+
+parse_args "$@"
 
 if [ -z "$MAIN_TABLE" ]; then
   echo "error: missing required flag -t|--table" >&2
   exit 1
 fi
 
-MAIN_ITEMS=$(query_database)
+# ╭──────────────────────
+# │ Main. Start here.
+# ╰────────
 
-if [ -z "$MAIN_ITEMS" ]; then
-  echo "[]"
-  exit 0
+query="SELECT ${FILTER:-*} FROM $MAIN_TABLE"
+
+if [ -n "$WHERE" ]; then
+  query="$query WHERE $WHERE"
 fi
 
-if [ -z "$RELATED" ]; then
-  echo "$MAIN_ITEMS"
-  exit 0
+if [ -n "$SORT" ]; then
+  query="$query ORDER BY $SORT"
 fi
 
-attach_related_models
+MAIN_ITEMS=$(sqlite3 "$OPENAI_DB_FILE" \
+  "$(echo "-${MODE:-json}")" \
+  "$query"
+)
 
-echo "$MAIN_ITEMS"
+if [ -n "$RELATED" ]; then
+  attach_related_models
+fi
+
+printf "%s\n" "$MAIN_ITEMS"
+
diff --git a/new/modules/openai/libs/sqlite-orm/ai-db-has-field b/new/modules/openai/libs/sqlite-orm/ai-db-has-field
--- a/new/modules/openai/libs/sqlite-orm/ai-db-has-field
+++ b/new/modules/openai/libs/sqlite-orm/ai-db-has-field
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
 # NAME 
 #  ai-db-has-field - Check if a table has a given field
@@ -7,8 +7,8 @@
 #  ai-db-has-field <-t table_name> <-f field_name>
 #
 # DESCRIPTION
-#  Check if a table has a given field. Returns 0 if the field exists, 1 if it
-#  does not.
+#  Check if a table has a given field. 
+#  Returns 0 if the field exists, 1 if it does not.
 #
 # OPTIONS
 #  -t, --table <table_name>
@@ -30,7 +30,20 @@
 # SEE ALSO
 #  sqlite3(1)
 
-# Parse flags
+does_table_exist() {
+  sqlite3 "$OPENAI_DB_FILE" \
+    "SELECT name FROM sqlite_master WHERE type='table'" \
+  | grep -c "$1" > /dev/null
+}
+
+does_field_exist() {
+  sqlite3 --json "$OPENAI_DB_FILE" "PRAGMA table_info($1)" \
+  | jq -r '.[].name' \
+  | grep -c "$2" > /dev/null
+}
+
+# ╭───┤ Input validation
+# ╰─
 while [ "$#" -gt 0 ]; do
   case $1 in
     -t|--table) 
@@ -50,16 +63,12 @@ while [ "$#" -gt 0 ]; do
       fi
     ;;
     --) shift; break ;;
-    -?*) 
-      echo "error: unknown flag $1" >&2
-      exit 1
-    ;;
+    -?*) echo "error: unknown flag $1" >&2; exit 1 ;;
     *) break ;;
   esac
   shift
 done
 
-# Input validation
 if [ -z "$table" ]; then
   echo "error: missing required flag -t|--table" >&2
   exit 1
@@ -70,21 +79,15 @@ if [ -z "$field" ]; then
   exit 1
 fi
 
-# Functions
-get_all_table_names() {
-  sqlite3 "$OPENAI_DB_FILE" "SELECT name FROM sqlite_master WHERE type='table';"
-}
+# ╭──────────────────────
+# │ Main. Start here.
+# ╰────────
 
-get_field_names() {
-  sqlite3 --json "$OPENAI_DB_FILE" "PRAGMA table_info($1);" | jq -r '.[].name'
-}
-
-# Main
-if ! get_all_table_names | grep -c "$table" > /dev/null; then
+if ! does_table_exist "$table"; then
   echo "error: table $table does not exist" >&2
   exit 2
 fi
 
-if ! get_field_names "$table" | grep -c "$field" > /dev/null; then
+if ! does_field_exist "$table" "$field"; then
   exit 3
 fi
diff --git a/new/modules/openai/libs/sqlite-orm/ai-db-update b/new/modules/openai/libs/sqlite-orm/ai-db-update
--- a/new/modules/openai/libs/sqlite-orm/ai-db-update
+++ b/new/modules/openai/libs/sqlite-orm/ai-db-update
@@ -1,6 +1,6 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
-. "$CORE_LIBS/stdin-or"
+. "$CORE_FUNCTIONS/stdin-or"
 
 # NAME
 #  ai-db-update - Update one or more records in a given table
@@ -35,7 +35,8 @@
 # SEE ALSO
 #  sqlite3(1), jq(1)
 
-# Parse flags
+# ╭───┤ Input validation
+# ╰─
 while [ "$#" -gt 0 ]; do
   case $1 in
     -t|--table)
@@ -61,7 +62,6 @@ while [ "$#" -gt 0 ]; do
   shift
 done
 
-# Input validation
 if [ -z "$table" ]; then
   echo "error: missing required flag -t|--table" >&2
   exit 1
@@ -73,15 +73,19 @@ if [ -z "$where" ]; then
 fi
 
 json_data=$(stdin_or "$1")
-if [ -z "$json_data" ]; then
-  echo "error: missing required argument [json_data]" >&2
+if [ -z "$json_data" ] || [ "$json_data" = "{}" ]; then
+  echo "error: missing or empty required argument json_data" >&2
   exit 1
 fi
 
-# Main
-update_statement=$(echo "$json_data" \
+# ╭──────────────────────
+# │ Main. Start here.
+# ╰────────
+
+update_statement=$(printf "%s" "$json_data" \
   | jq --raw-output \
     --arg table "$table" \
+    --arg where "$where" \
   "# Function to escape string for SQLite
   def sqlite_escape:
     if type == \"string\" then
@@ -90,15 +94,10 @@ update_statement=$(echo "$json_data" \
       tostring
     end;
 
-  # Extract keys and process values in a consistent order
-  to_entries | 
-    map(.key) as \$keys |
-    map(.value | sqlite_escape) as \$values |
-
-  # Build SQL update statement
+  # Build SQL update statement by setting each key to its corresponding value
   \"UPDATE \(\$table) SET \" +
-    (\$keys | map(\"\(. | sqlite_escape) = ?\") | join(\", \")) +
-  \" WHERE $where;\""
+    (to_entries | map(\"\(.key)='\" + (.value | sqlite_escape) + \"'\") | join(\", \")) +
+  \" WHERE \(\$where);\""
 )
 
 if [ $? -ne 0 ]; then
@@ -106,6 +105,4 @@ if [ $? -ne 0 ]; then
   exit 2
 fi
 
-data=$(sqlite3 --json "$OPENAI_DB_FILE" "$update_statement")
-
-echo "$data" | jq --raw-output --compact-output --monochrome-output '.[0]'
+sqlite3 --json "$OPENAI_DB_FILE" "$update_statement"
diff --git a/new/modules/openai/scripts/ai-recall b/new/modules/openai/scripts/ai-recall
--- a/new/modules/openai/scripts/ai-recall
+++ b/new/modules/openai/scripts/ai-recall
@@ -1,45 +1,106 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
-. "$CORE_LIBS/stdin-or"
+set -e
 
 # NAME
-#  ai-resume - Set the current conversation as the active one and output the
-#  conversation messages 
+#  ai-recall - Set the active conversation
 #
 # SYNOPSIS
-#  ai-resume <conversation_id>
+#  ai-recall [choose | view <conversation_id>] 
 #
 # DESCRIPTION
 #  Preview a conversation by displaying all messages in the conversation, nicely
 #  formatted in markdown.
 #
-# ARGUMENTS
-#  <conversation_id>
-#   The ID of the conversation to preview.
+#  If no conversation_id argument is provided, a list of conversations is
+#  displayed and the user can select one.
+#
+#  Upon selecting the conversation, it is set as the active conversation and
+#  subsequent messages to `ai` will be added to this conversation.
+# 
+# COMMANDS
+#  choose
+#   Display a list of conversations and let the user select one.
+#
+#  view <conversation_id>
+#   Display the conversation with the given ID.
 #
 # EXAMPLES
-#  ai-resume 42
+#  ai-recall view 42
 #
 # SEE ALSO
-#  ai-db-find-many(1), jq(1), bat(1) 
+#  ai-db-find-many(1), jq(1), fzf(1), bat(1)
 
-conversation_id=$(stdin_or "$1")
+choose_conversation() {
+  delimiter="::"
 
-if [ -z "$conversation_id" ]; then
-  echo "error: missing argument <conversation_id>" >&2
-  exit 1
-fi
-
-ai-db-find-many \
-  --table Messages \
-  --where "conversations_id = $conversation_id" \
-  --include Users \
+  ai-db-find-many --table Conversations \
+    --filter "id, title, messages_count" \
+    --sort "updated_at DESC" \
   | jq --raw-output \
-    --arg ai_icon "$OPENAI_ICON" \
-    --arg human_icon "" \
-    '.[] | if .Users.is_ai == 1 then 
-      "## _\($ai_icon) \(.Users.name)_\n\(.content)\n" 
-    else 
-      "## \($human_icon) \(.Users.name)\n\(.content)\n"
-    end' \
-  | bat --language markdown --paging never --style numbers --color always 
+    --arg delimiter "$delimiter" \
+    '.[] | (.id|tostring) + $delimiter + .title + " (" + (.messages_count|tostring) + ")"' \
+  | fzf \
+    --delimiter "$delimiter" \
+    --with-nth "2" \
+    --print-query \
+    --header "$OPENAI_ICON Select a conversation to resume:" \
+    --preview 'ai-recall view {1}' \
+    --preview-window 'right:60%:wrap' \
+  | awk -F "$delimiter" '{print $1}' \
+  | tr -d '\n'
+}
+
+pretty_print_conversation() {
+  ai-db-find-many \
+    --table Messages \
+    --where "conversations_id = $CID" \
+    --include Users \
+    | jq --raw-output \
+      --arg ai_icon "$OPENAI_ICON" \
+      --arg human_icon "" \
+      '.[] | if .Users.is_ai == 1 then
+        "╭───────\n│ _\($ai_icon) \(.Users.name)_\n╰─────\n\(.content)\n"
+      else
+        "╭───────\n│ **\($human_icon) \(.Users.name)**\n╰─────\n\(.content)\n"
+      end' \
+    | bat --language markdown \
+      --paging never \
+      --style plain \
+      --color always
+}
+
+# ╭──────────────────────
+# │ Main 
+# ╰────────
+
+case "${1:-choose}" in
+  choose) 
+    CID=$(choose_conversation)
+
+    if [ -z "$CID" ]; then
+      echo "error: no conversation selected" >&2
+      exit 1
+    fi
+
+    ai-db-update \
+      --table Settings \
+      --where "key='active-conversation-id'" \
+      "{\"value\":$CID}"
+
+    clear
+    pretty_print_conversation
+  ;;
+  view)
+    CID="$2"
+    
+    if [ -z "$CID" ]; then
+      echo "error: missing required argument <conversation_id>" >&2
+      exit 1
+    fi
+
+    pretty_print_conversation
+  ;;
+  *) echo "Command \"$1\" not recognized" >&2; exit 1 ;;
+esac
+
diff --git a/new/modules/openai/training/sh/subshell-var-shadowing/prompt_script b/new/modules/openai/training/sh/subshell-var-shadowing/prompt_script
--- a/new/modules/openai/training/sh/subshell-var-shadowing/prompt_script
+++ b/new/modules/openai/training/sh/subshell-var-shadowing/prompt_script
@@ -1,7 +1,5 @@
 #!/usr/bin/env sh
 
-. "$CORE_LIBS/die"
-
 # NAME
 #  pinger - Rudimentary load testing tool for HTTP servers
 #
@@ -25,21 +23,24 @@ parse_args() {
     case $1 in
       -u|--url)
         if [ "$2" ] && [ "${2#-}" = "$2" ]; then URL=$2; shift; else
-          die 'ERROR: "--url" requires a non-empty option argument.'
+          echo 'ERROR: "--url" requires a non-empty option argument.' >&2
+          exit 1
         fi
       ;;
       -s|--sleep)
         if [ "$2" ] && [ "${2#-}" = "$2" ]; then SLEEP=$2; shift; else
-          die 'ERROR: "--sleep" requires a non-empty option argument.'
+          echo 'ERROR: "--sleep" requires a non-empty option argument.' >&2
+          exit 1
         fi
       ;;
       -c|--concurrency)
         if [ "$2" ] && [ "${2#-}" = "$2" ]; then CONCURRENCY=$2; shift; else 
-          die 'ERROR: "--concurrency" requires a non-empty option argument.'
+          echo 'ERROR: "--concurrency" requires a non-empty option argument.' >&2
+          exit 1
         fi
       ;;
       --) shift; break ;;
-      -?*) die "ERROR: Unknown option: $1" ;;
+      -?*) echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
       *) break ;;
     esac
     shift
@@ -48,11 +49,13 @@ parse_args() {
 
 validate_args() {
   if [ -z "$URL" ]; then
-    die "ERROR: URL is required."
+    echo "ERROR: URL is required." >&2
+    exit 1
   fi
 
   if [ "$SLEEP" -lt 0 ]; then
-    die "ERROR: Sleep must be a positive integer, got $SLEEP."
+    echo "ERROR: Sleep must be a positive integer, got $SLEEP." >&2
+    exit 1
   fi
 }
 
