refactor(core): streamline initialization and script improvements
- Update `modules/@1_core/.init` to remove redundant directory creation and simplify function sourcing
- Rename `modules/@1_core/.packages` to `modules/@1_core/packages.csv` for clarity
- Modify `modules/@1_core/scripts/datetime/has-days-passed` to use `/tmp` directory and improve error handling
- Update `modules/@1_core/scripts/doomst` and `modules/@1_core/scripts/yank` to source functions from `fancy-posix-utils` instead of `fancy-cli`
- Change shebang in `modules/@1_core/scripts/git-download` to use `sh` instead of `dash`
- Remove obsolete `modules/@1_core/functions/add-to-path` and `modules/@1_core/scripts/has-file-changed`

diff --git a/modules/@1_core/scripts/datetime/has-days-passed b/modules/@1_core/scripts/datetime/has-days-passed
--- a/modules/@1_core/scripts/datetime/has-days-passed
+++ b/modules/@1_core/scripts/datetime/has-days-passed
@@ -66,14 +66,15 @@ name="${name:-$1}"
 count="${count:-$2}"
 
 if [ -z "$name" ]; then
-  die '"--name" is required.'
+  fancy-log error '"--name" is required.'
+  exit 1
 fi
 
 if [ -z "$count" ] || [ "$count" -lt 1 ]; then 
   count=1
 fi
 
-past_value_file="$CORE_TMP/hdp_$name"
+past_value_file="/tmp/hdp_$name"
 past_value=$(cat "$past_value_file" 2> /dev/null || echo 0)
 now_in_seconds=$(date +%s)
 seconds_in_a_day=86400
