chore(shellai): auto format scripts using shfmt

diff --git a/modules/shellai/scripts/ai b/modules/shellai/scripts/ai
--- a/modules/shellai/scripts/ai
+++ b/modules/shellai/scripts/ai
@@ -22,12 +22,12 @@
 #
 #  recall
 #   Choose a conversation to set as the active one.
-# 
+#
 # OPTIONS
-#  --no-highlight 
+#  --no-highlight
 #   Do not syntax highlight the response.
 #
-# EXAMPLES 
+# EXAMPLES
 #  ai "What is the meaning of life?"
 #   Simple question
 #
@@ -39,8 +39,8 @@
 #
 #  cat "42.js" | ai "Explain what this does:"
 #   Concatenate both stdin and argument: <argument>\n\n<stdin>
-#  
-#  ai new "Let's start a new conversation, shall we?" 
+#
+#  ai new "Let's start a new conversation, shall we?"
 #   Start a new conversation
 #
 #  cat "42.js" | ai new "Explain what this does:"
@@ -49,7 +49,7 @@
 #
 #  ai recall
 #   Choose a conversation to set as the active one
-#  
+#
 # SEE ALSO
 #  ai-db-find-one(1), ai-db-find-many(1), ai-db-create(1), ai-db-update(1),
 #  jq(1), bat(1), sqlite3(2)
@@ -84,7 +84,7 @@ choose_agent() {
     | awk -F "$delimiter" '{print $1}'
 }
 
-# Create a new conversation and set it as the active one, so that subsequent 
+# Create a new conversation and set it as the active one, so that subsequent
 # messages are added automatically to it.
 #
 # SYNOPSIS
@@ -112,7 +112,7 @@ create_new_conversation() {
 #  2 Active conversation does not exist
 print_active_conversation() {
   cid=$(ai-db-find-one --mode csv --table Settings \
-        --filter "value" --where "key = 'active-conversation-id'")
+    --filter "value" --where "key = 'active-conversation-id'")
 
   if [ -z "$cid" ]; then
     fancy-log error "No active conversation set"
@@ -135,8 +135,14 @@ has_syntax_highlight="true"
 while [ "$#" -gt 0 ]; do
   case $1 in
     --no-highlight) has_syntax_highlight="" ;;
-    --) shift; break ;;
-    -?*) echo "error: unknown flag $1" >&2; exit 1 ;;
+    --)
+      shift
+      break
+      ;;
+    -?*)
+      echo "error: unknown flag $1" >&2
+      exit 1
+      ;;
     *) break ;;
   esac
   shift
@@ -147,23 +153,23 @@ query_arg=$1
 should_create=false
 
 case "$1" in
-  new) 
+  new)
     should_create=true
-    query_arg=$2 
+    query_arg=$2
 
     if [ -z "$query_arg" ] && [ -z "$query_stdin" ]; then
       fancy-log error "Please provide a query"
       exit 1
     fi
-  ;;
+    ;;
   recall)
     ai-recall
     exit 0
-  ;;
+    ;;
   retry)
     should_retry=true
     query_arg="dummy-content"
-  ;;
+    ;;
 esac
 
 if [ -z "$query_arg" ] && [ -z "$query_stdin" ]; then
@@ -183,7 +189,7 @@ fi
 # ╰────────
 
 active_cid=$(ai-db-find-one --mode csv --table Settings \
-    --filter "value" --where "key = 'active-conversation-id'")
+  --filter "value" --where "key = 'active-conversation-id'")
 
 if [ -z "$active_cid" ] && [ "$should_create" = false ]; then
   fancy-log warn --no-border "Cannot resume conversation because no active conversation is set, continuing by creating new conversation"
@@ -207,7 +213,7 @@ else
     CID=$(create_new_conversation "$agent_id")
   else
     agent_id=$(ai-db-find-one --mode csv --table Conversations \
-      --where "id=$CID" --filter "main_agent_id") 
+      --where "id=$CID" --filter "main_agent_id")
   fi
 fi
 
@@ -278,12 +284,13 @@ fi
 
 # ╭───┤ Prepare messages array for OpenAI POST request
 # ╰─
-messages=$(ai-db-find-many --table Messages \
-  --where "conversations_id = $CID" \
-  --sort "created_at ASC" \
-  --include "Users" \
-  | jq --raw-output --compact-output \
-    'def determineRole: 
+messages=$(
+  ai-db-find-many --table Messages \
+    --where "conversations_id = $CID" \
+    --sort "created_at ASC" \
+    --include "Users" \
+    | jq --raw-output --compact-output \
+      'def determineRole: 
       if .role != null and .role != "" then 
         .role 
       else 
@@ -329,7 +336,7 @@ exit_gracefully() {
   exit 0
 }
 
-trap exit_gracefully EXIT 
+trap exit_gracefully EXIT
 
 AGENT_MODEL=$(printf "%s" "$AGENT" | jq --raw-output '.model')
 AGENT_TEMPERATURE=$(printf "%s" "$AGENT" | jq --raw-output '.temperature')
@@ -341,7 +348,7 @@ ai-provider-openai --messages "$messages" \
   --temperature "$AGENT_TEMPERATURE" \
   | tee "$TMP_FILE" \
   | if [ -n "$has_syntax_highlight" ]; then
-      bat --unbuffered --language markdown --paging never --style plain
-    else
-      cat
-    fi
+    bat --unbuffered --language markdown --paging never --style plain
+  else
+    cat
+  fi
diff --git a/modules/shellai/scripts/openai-api/ai-provider-openai b/modules/shellai/scripts/openai-api/ai-provider-openai
--- a/modules/shellai/scripts/openai-api/ai-provider-openai
+++ b/modules/shellai/scripts/openai-api/ai-provider-openai
@@ -4,7 +4,7 @@
 #  ai-provider-openai - Interface for OpenAI's /chat/completions endpoint.
 #
 # SYNOPSIS
-#  ai-provider-openai <-m|--messages> <messages> [--no-stream] 
+#  ai-provider-openai <-m|--messages> <messages> [--no-stream]
 #
 # DESCRIPTION
 #  Low-level script calling the OpenAI API to get completions for a given
@@ -35,15 +35,15 @@
 #
 # ENVIRONMENT
 #  OPENAI_API_KEY
-#   The API key used for authenticating with the OpenAI API. 
+#   The API key used for authenticating with the OpenAI API.
 #
 #  OPENAI_ORG_ID
 #   The organization ID used for authenticating with the OpenAI API.
-# 
+#
 # SEE ALSO
 #  curl(1), jq(1)
 
-# ╭───┤ Outside dependencies 
+# ╭───┤ Outside dependencies
 # ╰─
 if [ -z "$OPENAI_API_KEY" ]; then
   echo "error: missing required environment variable OPENAI_API_KEY" >&2
@@ -63,47 +63,57 @@ while [ "$#" -gt 0 ]; do
   case $1 in
     --raw)
       should_output_raw="true"
-    ;;
+      ;;
     --debug)
       is_debug="true"
-    ;;
+      ;;
     --no-stream)
       should_stream=""
-    ;;
-    -mt|--max-tokens)
+      ;;
+    -mt | --max-tokens)
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
-        max_tokens=$2; shift
+        max_tokens=$2
+        shift
       else
         echo 'error: argument --max-tokens requires value.' >&2
         exit 1
       fi
-    ;;
-    -msg|--messages)
+      ;;
+    -msg | --messages)
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
-        messages=$2; shift
+        messages=$2
+        shift
       else
         echo 'error: argument --messages requires value.' >&2
         exit 1
       fi
-    ;;
-    -t|--temperature)
+      ;;
+    -t | --temperature)
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
-        temperature=$2; shift
+        temperature=$2
+        shift
       else
         echo 'error: argument --temperature requires value.' >&2
         exit 1
       fi
-    ;;
-    -m|--model)
+      ;;
+    -m | --model)
       if [ "$2" ] && [ "${2#-}" = "$2" ]; then
-        model=$2; shift
+        model=$2
+        shift
       else
         echo 'error: argument --model requires value.' >&2
         exit 1
       fi
-    ;;
-    --) shift; break ;;
-    -?*) echo "error: unknown flag: $1" >&2; exit 1 ;;
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -?*)
+      echo "error: unknown flag: $1" >&2
+      exit 1
+      ;;
     *) break ;;
   esac
   shift
@@ -115,7 +125,7 @@ fi
 
 if [ -z "$messages" ]; then
   echo "error: missing -m|--messages argument or stdin input" >&2
-  exit 1 
+  exit 1
 fi
 
 # ╭───┤ Functions
@@ -131,7 +141,7 @@ extract_streaming_content() {
     -e 's/^data: //' \
     -e 's/\[DONE\]//g' \
     | jq --unbuffered --raw-output --join-output \
-      'select(.choices[0].delta.content != null) | .choices[0].delta.content' 
+      'select(.choices[0].delta.content != null) | .choices[0].delta.content'
 }
 
 # Extract the content string from the non-streamed response.
@@ -153,7 +163,7 @@ else
   curl_stream_flags="--silent"
 fi
 
-if [ -n "$is_debug" ]; then 
+if [ -n "$is_debug" ]; then
   print-info -nb "should_stream: ${should_stream:-false}"
   print-info -nb "should_output_raw: ${should_output_raw:-false}"
   print-info -nb "temperature: $temperature"
@@ -179,20 +189,20 @@ jq --compact-output --null-input \
       end
     )
   }' \
- | curl --silent "$curl_stream_flags" \
-  --data @- \
-  --fail-with-body \
-  --request POST \
-  --header "Content-Type: application/json" \
-  --header "Authorization: Bearer $OPENAI_API_KEY" \
-  --header "OpenAI-Organization: $OPENAI_ORG_ID" \
+  | curl --silent "$curl_stream_flags" \
+    --data @- \
+    --fail-with-body \
+    --request POST \
+    --header "Content-Type: application/json" \
+    --header "Authorization: Bearer $OPENAI_API_KEY" \
+    --header "OpenAI-Organization: $OPENAI_ORG_ID" \
     https://api.openai.com/v1/chat/completions \
   | if [ -n "$should_output_raw" ]; then
-      cat
+    cat
+  else
+    if [ -n "$should_stream" ]; then
+      extract_streaming_content
     else
-      if [ -n "$should_stream" ]; then
-        extract_streaming_content
-      else
-        extract_content
-      fi
+      extract_content
     fi
+  fi
