feat: explicitly set dash instead of sh

diff --git a/new/modules/@core/scripts/frontmatter b/new/modules/@core/scripts/frontmatter
--- a/new/modules/@core/scripts/frontmatter
+++ b/new/modules/@core/scripts/frontmatter
@@ -1,6 +1,4 @@
-#!/usr/bin/env sh
-
-. "$CORE_LIBS/die"
+#!/usr/bin/env dash
 
 print_help() {
   cat <<EOF
@@ -47,11 +45,12 @@ parse_args() {
         if [ "$2" ] && [ "${2#-}" = "$2" ]; then
           FIELDS="$FIELDS $2"; shift
         else
-          die 'ERROR: "--field" requires a non-empty option argument.'
+          echo 'ERROR: "--field" requires a non-empty option argument.' >&2
+          exit 1
         fi
       ;;
       --) shift; break ;;
-      -?*) print_help >&2; die "ERROR: Unknown option: $1" ;;
+      -?*) print_help >&2; echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
       *) break ;;
     esac
     shift
@@ -93,7 +92,8 @@ extract_frontmatter() {
 ##
 
 if [ "$#" -lt 1 ]; then
-  die "ERROR: A file argument is required."
+  echo "ERROR: A file argument is required." >&2
+  exit 1
 fi
 
 FIELDS=""
diff --git a/new/modules/@core/scripts/jot b/new/modules/@core/scripts/jot
--- a/new/modules/@core/scripts/jot
+++ b/new/modules/@core/scripts/jot
@@ -1,15 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
-# The path to store the last note's location
-LAST_NOTE_PATH_FILE="${HOME}/.jot/last_note_path"
+# ╭───┤ Input variables
+# ╰─
+prev_note_path="${HOME}/.jot/last_note_path"
+should_continue=false
 
-# Flag to determine if continuing from the last note
-SHOULD_CONTINUE=false
-
-# Create .jot own directory if it doesn't exist
-[ ! -d "${HOME}/.jot" ] && mkdir "${HOME}/.jot"
-
-# Parse arguments
+# ╭───┤ Parse flags 
+# ╰─
 while [ "$#" -gt 0 ]; do
   case "$1" in
     -h|--help)
@@ -17,29 +14,36 @@ while [ "$#" -gt 0 ]; do
       exit 0
     ;;
     -c|--continue)
-      SHOULD_CONTINUE=true
+      should_continue=true
       shift
     ;;
     --) shift; break ;;
-    -?*)
-      echo "error: unknown flag: $1" >&2
-      exit 1
-    ;;
+    -?*) echo "error: unknown flag: $1" >&2; exit 1 ;;
     *) break ;;
   esac
 done
 
-# Determine the file to edit
-if [ "$SHOULD_CONTINUE" = true ] && [ -f "$LAST_NOTE_PATH_FILE" ]; then
-  tmp_file=$(cat "$LAST_NOTE_PATH_FILE" 2>/dev/null)
+# ╭──────────────────────
+# │ Main. Start here.
+# ╰────────
+
+[ ! -d "${HOME}/.jot" ] && mkdir "${HOME}/.jot"
+
+# Decide on the tmp file to edit.
+# Either the last one, from a previous jot, or create a new one.
+if [ "$should_continue" = true ] && [ -f "$prev_note_path" ]; then
+  tmp_file=$(cat "$prev_note_path" 2>/dev/null)
 fi
 
 if [ -z "$tmp_file" ]; then
   tmp_file=$(mktemp /tmp/jot.XXXXXX)
 fi
 
-# Open the file in editor, in a centered terminal window
-alacritty --title layout-center \
+# Open Nvim, in edit mode, inside a alacritty terminal window. The class is
+# used to center the window on the screen and is configured by the window
+# manager, i3 in this case.
+alacritty --title "Jot It Down - $tmp_file" \
+  --class "center-float" \
   --command nvim \
     -c "setlocal syntax=markdown" \
     -c "setlocal wrap" \
@@ -47,13 +51,11 @@ alacritty --title layout-center \
     -c "startinsert" \
     "$tmp_file"
 
+# Persist the note for next time
 text=$(cat "$tmp_file")
-
-# If text was entered, print it and persist the file in case user wants to
-# continue editing it later
 if [ -n "$text" ]; then
   printf "%s" "$text"
-  echo "$tmp_file" > "$LAST_NOTE_PATH_FILE" # Update the last note path
+  echo "$tmp_file" > "$prev_note_path"
 else
   echo "error: no text was entered" >&2
   exit 1
diff --git a/new/modules/@core/scripts/pinger b/new/modules/@core/scripts/pinger
--- a/new/modules/@core/scripts/pinger
+++ b/new/modules/@core/scripts/pinger
@@ -1,6 +1,6 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
-. "$CORE_LIBS/die"
+set -e
 
 # NAME
 #  pinger - Rudimentary load testing tool for HTTP servers
@@ -25,21 +25,24 @@ parse_args() {
     case $1 in
       -u|--url)
         if [ "$2" ] && [ "${2#-}" = "$2" ]; then URL=$2; shift; else
-          die 'ERROR: "--url" requires a non-empty option argument.'
+          echo 'error: "--url" requires a non-empty option argument.' >&2
+          exit 1
         fi
       ;;
       -s|--sleep)
         if [ "$2" ] && [ "${2#-}" = "$2" ]; then SLEEP=$2; shift; else
-          die 'ERROR: "--sleep" requires a non-empty option argument.'
+          echo 'error: "--sleep" requires a non-empty option argument.' >&2
+          exit 1
         fi
       ;;
       -c|--concurrency)
         if [ "$2" ] && [ "${2#-}" = "$2" ]; then CONCURRENCY=$2; shift; else 
-          die 'ERROR: "--concurrency" requires a non-empty option argument.'
+          echo 'error: "--concurrency" requires a non-empty option argument.' >&2
+          exit 1
         fi
       ;;
       --) shift; break ;;
-      -?*) die "ERROR: Unknown option: $1" ;;
+      -?*) echo "error: Unknown option: $1" >&2; exit 1 ;;
       *) break ;;
     esac
     shift
@@ -48,11 +51,13 @@ parse_args() {
 
 validate_args() {
   if [ -z "$URL" ]; then
-    die "ERROR: URL is required."
+    echo "error: URL is required." >&2
+    exit 1
   fi
 
   if [ "$SLEEP" -lt 0 ]; then
-    die "ERROR: Sleep must be a positive integer, got $SLEEP."
+    echo "error: Sleep must be a positive integer, got $SLEEP." >&2
+    exit 1
   fi
 }
 
diff --git a/new/modules/snippets/scripts/snippets b/new/modules/snippets/scripts/snippets
--- a/new/modules/snippets/scripts/snippets
+++ b/new/modules/snippets/scripts/snippets
@@ -1,13 +1,12 @@
-#!/usr/bin/env sh
+#!/usr/bin/env dash
 
 # -e: exit on error, -u: error on undefined variable
-set -eu
+set -u
 
-. "$CORE_LIBS/stdin-or"
-. "$CORE_LIBS/die"
+. "$CORE_FUNCTIONS/stdin-or"
 
 # List all snippet files in the snippets directory.
-list() {
+list_all() {
   show_only_runnable=false
 
   while [ "$#" -gt 0 ]; do
@@ -16,7 +15,7 @@ list() {
         show_only_runnable=true
       ;;
       --) shift; break ;;
-      -?*) die "Unknown option (ignored): $1" ;;
+      -?*) echo "error: unknown option (ignored): $1" >&2; exit 1 ;;
       *) break ;;
     esac
     shift
@@ -61,7 +60,8 @@ run() {
   path="$SNIPPETS_DATA/${name}"
 
   if [ ! -f "$path" ]; then
-    die "Snippet <u>${name}</u> does not exist in <u>${SNIPPETS_DATA}</u>"
+    echo "Snippet $name does not exist in $SNIPPETS_DATA" >&2
+    exit 1
   fi
 
   if [ -x "$path" ]; then
@@ -78,8 +78,6 @@ run() {
 # Arguments:
 # $1: Snippet file path
 open() {
-  name=$(stdin_or "$1")
-
   if [ ! -f "$1" ]; then
     {
       echo "\`\`\`toml" 
@@ -90,23 +88,21 @@ open() {
       echo "created_at=\"$(date --iso-8601=seconds)\""
       echo "\`\`\`"
       echo ""
-    } > "$1"
+    } > "$SNIPPETS_DATA/$1"
   fi
 
   # Set nvim's NerdTree file explorer to the snippets directory
-  cd "$SNIPPETS_DATA"
-
-  nvim \
+  cd "$SNIPPETS_DATA" && nvim \
     -c "norm zz" \
     -c "set spell" \
     -c "set syntax=markdown" \
-    "$name"
+    "$1"
 }
 
 # Ask the user to select a snippet from a list of snippets. If no mached 
 # snippet is found, the user's query is returned.
 # Synopsis: choose_snippet <title>
-choose_snippet() {
+choose() {
   title="$1"
   delimiter_count=$(echo "$SNIPPETS_DATA" \
     | grep --only-matching "/" \
@@ -121,6 +117,7 @@ choose_snippet() {
       --with-nth=$(( delimiter_count + 2 )) \
       --print-query
     )
+
   query=$(echo "$choice" | head -n 1)
   path=$(echo "$choice" | tail -n 1)
 
@@ -131,16 +128,20 @@ choose_snippet() {
   fi
 }
 
+# ╭──────────────────────
+# │ Main 
+# ╰────────
+
 case ${1-copy} in
   list) 
     shift
-    list "$@"
+    list_all "$@"
   ;;
   run)
     run "$2"
   ;;
   copy)
-    path=$(choose_snippet " copy snippet:")
+    path=$(choose " copy snippet:")
 
     if [ -n "$path" ] && [ -f "$path" ]; then
       # not using pipe (run "$snippet" | copy) since some snippets may output 
@@ -149,13 +150,11 @@ case ${1-copy} in
     fi
   ;;
   upsert)
-    path=$(choose_snippet "󱩼 edit or create snippet:")
+    path=$(choose "󱩼 edit or create snippet:")
 
     if [ -n "$path" ]; then
       open "$path"
     fi
   ;;
-  *) 
-    die "Command <u>$1</u> not defined"
-  ;;
+  *) echo "error: command $1 not defined" >&2; exit 1 ;;
 esac
